.TH ALLEGRO 6 "November 18, 2000"
.SH NAME
all-demo \- Allegro's demonstration game
.SH SYNOPSIS
.B allegro
.RI
.SH DESCRIPTION
This is a simple game which demonstrates some features of the Allegro
library, but it is also fully playable. The source is contained in the
liballegro-doc package.
.PP
Use arrow buttons (left, right, up) to control your ship.
.PP
Allegro is gift-ware. It was created by a number of people working in
cooperation, and is given to you freely as a gift. You may use, modify,
redistribute, and generally hack it about in any way you like, and you do
not have to give us anything in return. However, if you like this product
you are encouraged to thank us by making a return gift to the Allegro
community. This could be by writing an add-on package, providing a useful
bug report, making an improvement to the library, or perhaps just
releasing the sources of your program so that other people can learn from
them. If you redistribute parts of this code or make a game using it, it
would be nice if you mentioned Allegro somewhere in the credits, but you
are not required to do this. We trust you not to abuse our generosity.
.PP
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.TP
.B \-cheat \ \ \ \ 
Self explanatory...
.TP
.B \-turbo \ \ \ \ 
acceleration is always on - lucky when your ship survive longer than 60
seconds.
.TP
.B \-jumpstart
faster fadings
.SH AUTHOR
This manual page was written by Eduard Bloch <blade@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
