.TH ALLEGRO 1 "8 June 2003" Version 4.0.3
.SH NAME
allegro-examples - small example programs to demonstrate the power of Allegro
.SH SYNOPSIS
.B allegro-examples
.br
.B playfli-from-Allegro
[OPTIONS]
.br
.B midikeyboard-from-Allegro
.br
.B calculator-from-Allegro
.br

.SH DESCRIPTION
.PP

allegro-examples is a small overview program, used to start misc.
examples. Tree of them can be called directly from the command line:
playfli-from-Allegro (player for FLI/FLC animations),
midikeyboard-from-Allegro (midi keyboard), calculator-from-Allegro
(small graphical calculator).

.SH SEE ALSO
.BR allegro-config (1)
.br
The
.BR allegro
info entry
.br
Additional documentation and example files are contained in the liballegro-doc package on Debian systems.
.SH COPYRIGHT
This manual page was   written   by   Eduard   Bloch <blade@debian.org>,
for the Debian GNU/Linux  system  (but may be used by others).
