.TH ALLEGRO 1 "8 June 2003" Version 4.0.3
.SH NAME
allegro-dev-tools - collection of useful tools for Allegro developers
.SH SYNOPSIS
.B colormap
[OPTIONS]
.br
.B dat
[OPTIONS]
.br
.B dat2s
[OPTIONS]
.br
.B exedat
[OPTIONS]
.br
.B grabber
[OPTIONS]
.br
.B pack
[OPTIONS]
.br
.B pat2dat
[OPTIONS]
.br
.B rgbmap
[OPTIONS]
.br
.B textconv
[OPTIONS]
.br

.SH DESCRIPTION
.PP

The listed tools are distributed with the Allegro package to help
developers on their work. They are intended to prepare some data
(pat2dat, rgbmap, textconf) or create and manage data files that are
used by the Allegro library (dat, dat2s, exedat, grabber, pack). Call
this programs from the command line to print some help about their
usage.
.SH SEE ALSO
.BR allegro-config (1)
.br
The
.BR allegro
info entry
.br
Additional documentation and example files are contained in the liballegro-doc package on Debian systems.
.SH COPYRIGHT
This manual page was   written   by   Eduard   Bloch <blade@debian.org>,
for the Debian GNU/Linux  system  (but may be used by others).
